language: node_js
node_js:
- stable
install: npm ci
deploy:
  provider: heroku
  app: catalactics-bot
  api_key:
    secure: G4JMNQlc17CHO001J//RHa8UzufH7T/VomWYrkbR+DbMhaFCWN5s6/ykO1LaOaAh5/Wtk19Ad4KDX+0JFJYWZHD8Iteez2/TO5o7eehYQJ72nFFExqU/5/YkEFTRpQr9jdy94b0HJoKmM0CnbYO66WVfHXCpo1wT68t0Y4nRs/k03gdjn5vBvF09OYa/LUakLUtSwHW0TXYFMI3/hrCd0qX1EJk37TBzdZnGmht5gbcOoGFZ/mpaEDaSiPlOkfJ9OvMtvkro+ZsL8BwgSv9UEiopUVCwmKOylHeh2v7wpRJkLEOBhwiGdsRsQxFXVrJnirTdoHutvKP2NR7tCJx+4k8Zhfb7gjT2mBmOAoCS0vSGAn1BYh7oesRvHbfV/b0nxbwKNOpqgYdYDlWTEFt4IRW+IQ40oEAEi99MTsZPKH4DVXY5nJ+c7HS+uVCKx/kuPFC6NLzHAvaEypgcetpKeyLisWiiSjMBia+s7kb0MHCavazPceDjRjl+QcpDimv0d3U22LzK/FaPf2iMt+3pcm0LHeDJTIz3OyIPDWUPhtXlQ7naanIkn3lO+QBtn+Q3VVCK2wjeHgyGC6S59FFWZ+IsBBomB0fu9OeMVkoz4dR/Rf/I7jImVwJ2Vo7GyqZIFqqfe6/UX4nway3TfscE0NkD1nIWeJBUCHx8z0/Oi0g=
