version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@1.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
   test and deploy:
     jobs:
       - test
       - heroku/deploy-via-git:
          requires:
          - test
          filters:
            branches:
              only: master
