name: Update Readme

on:
  push:
    branches: [ master ]

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Clean Install Dependencies
        run: npm ci

      - name: Install Typescript
        run: npm i typescript

      - name: Install ts-node
        run: npm i ts-node

      - name: Run Script (update-readme)
        run: npm run update-readme
        env:
          CI: true
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - name: Commit files
        run: |
          git config --local user.email "45566099+JoshuaPelealu@users.noreply.github.com"
          git config --local user.name "Joshua Pelealu"
          git add README.md
          git commit -m "Auto Update README.md"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'JoshuaPelealu/catalactics-bot-docs'


